before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - git config --global user.email "vincent@fishboneapps.com"
  - git config --global user.name "Vincent"
  - ssh-keyscan -t rsa gitlab.fishboneapps.com >> ~/.ssh/known_hosts

stages:
  - build

build_job:
  stage: build
  tags:
    - hexo
  script:
    - ls -al ~/.ssh
    - npm -g install hexo --no-optional
    - npm install --no-optional
    - hexo generate
    - hexo deploy
    - echo "Deploy succssed!"
  cache:
    key: ${CI_BUILD_REF_NAME}
    paths:
      - node_modules/