stages:
    - build
    - test
    - deploy

job1:
    stage: test
    tags:
        - hexo
    script:
        - echo "This is Job1"
        - echo "It's at test stage"

job2:
    stage: build
    tags:
        - hexo
    script:
        - echo "This is Job2"
        - echo "It's at build stage"

job3:
    stage: deploy
    tags:
        - hexo
    script:
        - echo "This is Job3"
        - echo "It's at deploy stage"