before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  ## Make sure that rsync is installed
  - 'which rsync || ( apt-get update -y && apt-get install rsync -y)'

stages:
  - build

build_job:
  stage: build
  tags:
    - hexo
  script:
    - ls -al ~/.ssh
    - npm -g install hexo -f --no-optional
    - npm install -f --no-optional
    - hexo clean
    - hexo generate
    - hexo deploy
    - echo "Deploy succssed!"
  cache:
    key: ${CI_BUILD_REF_NAME}
    paths:
      - node_modules/