before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - git config --global user.email "vincent@fishboneapps.com"
  - git config --global user.name "Vincent"

stages:
  - build

build_job:
  stage: build
  tags:
    - hexo
  script:
    - npm -g uninstall hexo
    - npm -g install hexo
    - npm install
    - hexo clean
    - hexo generate
    - hexo deploy
    - echo "Deploy succssed!"