image: node:12.16.1

stages:
  - build

build_job:
  stage: build
  tags:
    - hexo
  script:
    - npm install hexo -g
    - npm install
    - hexo clean
    - hexo generate
    - hexo deploy
    - echo "Deploy succssed!"