before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
  - ssh-keyscan -t rsa gitlab.fishboneapps.com >> ~/.ssh/known_hosts
  ## Make sure that rsync is installed
  - 'which rsync || ( apt-get update -y && apt-get install rsync -y)'

stages:
  - build

build_job:
  stage: build
  tags:
    - hexo
  script:
    - ls ~/.ssh
    - cat ~/.ssh/known_hosts
    - cat ~/.ssh/id_rsa
    - npm -g install hexo -f --no-optional
    - npm cache verify
    - npm install -f --no-optional
    - hexo cl && hexo g
    - hexo deploy
    - echo "Deploy succssed!"
  cache:
    key: ${CI_BUILD_REF_NAME}
    paths:
      - node_modules/