# Menus
menu:
    Home: /
    # Delete this row if you don't want categories in your header nav bar
    Categories:
    About: /about


# Customize
customize:
    logo:
        width: 165
        height: 80
        url: images/logo.png
    theme_color: '#d35'
    highlight: androidstudio
    sidebar: left # sidebar position, options: left, right
    thumbnail: true # enable posts thumbnail, options: true, false
    favicon: images/vincent.ico
    social_links: # for more icons, please see http://fontawesome.io/icons/#brand
        facebook-official: https://www.facebook.com/dtvgood202
        instagram: https://www.instagram.com/hdtvgood202
        github: https://github.com/TingSyuanWang
        twitter: https://twitter.com/dtvgood202
        google-plus-official: https://plus.google.com/116113761236955456663


# Widgets
widgets:
    - recent_posts
    - category
    - archive
    - tag
    - tagcloud
    - links

# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false

# Comment
comment:
    disqus: vincents-corner # enter disqus shortname here
    duoshuo: # enter duoshuo shortname here
    youyan: # enter youyan uid here

# Share
share: default # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
    fancybox: true # options: true, false
    scrollLoading: true # options: true, false
    google_analytics: # enter the tracking ID for your Google Analytics
    baidu_analytics: # enter Baidu Analytics hash key
    lightgallery: true

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id: 176717762750155
        fb_admins: 'dtvgood202'
        twitter_id:
        google_plus:
    links:
        Facebook: https://www.facebook.com/dtvgood202
